// research-tasks.js — auto-generated from research/queue.md
// 9 tasks (9 done, 0 pending)
const RESEARCH_TASKS = [
  {"id": "eaglesong-asic-prototyping-a7-lite", "status": "DONE", "priority": "HIGH", "goal": "Map out a practical path from the Eaglesong hash algorithm to an FPGA implementation on the MicroPhase A7-Lite Artix-7 board (XC7A35T/100T/200T) and then to early-stage ASIC design concepts, focusing on what this specific board can teach us about a future Eaglesong ASIC miner.", "tags": ["eaglesong", "fpga", "asic", "xilinx", "artix7", "mining"]},
  {"id": "eaglesong-artix7-rtl-core-design", "status": "DONE", "priority": "HIGH", "goal": "Design and document a clean, ASIC-friendly Eaglesong RTL core suitable for Artix-7 (MicroPhase A7-Lite class) including pipeline structure, resource estimates, and verification strategy.", "tags": ["eaglesong", "fpga", "artix7", "verilog", "rtl"]},
  {"id": "helium-anti-gaming-mechanisms-survey", "status": "DONE", "priority": "HIGH", "goal": "Survey known anti-gaming and anti-Sybil mechanisms used or proposed in the Helium network and similar wireless/proof-of-coverage systems, focusing on what actually worked, what was gamed, and why.", "tags": ["helium", "lora", "anti-gaming", "sybil", "incentives"]},
  {"id": "lora-poc-anti-gaming-design-for-ckb", "status": "DONE", "priority": "HIGH", "goal": "Sketch a set of protocol-level design patterns for a theoretical LoRa-based proof-of-coverage PoC on Nervos Network that explicitly minimise the kinds of gaming seen in Helium.", "tags": ["nervos", "ckb", "lora", "proof-of-coverage", "anti-gaming", "protocol-design"]},
  {"id": "eaglesong-fpga-power-perf-modelling", "status": "DONE", "priority": "MEDIUM", "goal": "Develop a simple method to estimate power consumption and performance for Eaglesong hash cores on Artix-7 FPGAs and use it to extrapolate rough ASIC design targets.", "tags": ["eaglesong", "fpga", "power", "performance", "modelling"]},
  {"id": "asic-design-flow-intro-for-fpga-dev", "status": "DONE", "priority": "MEDIUM", "goal": "Provide a concise, FPGA-developer-oriented introduction to the ASIC design flow, focused on what needs to change when moving an Eaglesong RTL core from Artix-7 to a real ASIC.", "tags": ["asic", "design-flow", "rtl", "synthesis"]},
  {"id": "microphase-a7-lite-board-deep-dive", "status": "DONE", "priority": "MEDIUM", "goal": "Collect and summarise all available documentation for the MicroPhase A7-Lite Xilinx Artix-7 FPGA Demo Board (XC7A35T/100T/200T variants), focusing on features and constraints relevant to implementing and measuring hash cores like Eaglesong.", "tags": ["fpga", "xilinx", "artix7", "microphase", "hardware"]},
  {"id": "wireless-poc-crypto-anti-gaming-patterns", "status": "DONE", "priority": "MEDIUM", "goal": "Identify general mechanism-design patterns across Helium and other wireless/proof-of-location projects that reduce gaming, and summarise which patterns are likely robust vs which ones failed.", "tags": ["helium", "lora", "proof-of-coverage", "crypto-economics", "mechanism-design"]},
  {"id": "asic-design-flow-intro-for-fpga-dev-revisit", "status": "DONE", "priority": "MEDIUM", "goal": "Re-research \"asic-design-flow-intro-for-fpga-dev\" with better seeds \u2014 initial crawl returned thin findings (poor seed URLs, 404s, or topic too broad). Find primary sources: official docs, GitHub raw source, spec sheets, RFCs, or forum posts with concrete answers.", "tags": []},
];